name: Jest Tests

on:
  push:
    branches:
      - '*'  # Trigger on all branches
  pull_request:
    branches:
      - '*'  # Trigger on all branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print current working directory
        run: pwd
      - name: List contents of current directory
        run: ls
      - name: Change working directory
        run: cd CM20314-ESP/cm20314

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci ## docs say generally faster than install

      - name: Run Jest tests
        run: npx jest -- --coverage
