name: Run tests

on: 
  pull_request:
    branches: ['main']

    workflow_dispatch:

  jobs:
    tests: 
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci ## docs say generally faster than install

      - name: Run Jest tests
        run: npx jest --coverage
      

